### ISSUE TITLE
Build on FreeBSD 8.4 fails, sequence of #includes in src/networking.c (with patch)

### ISSUE THREAD

**Issue by opsec** [armon/statsite#100]
--- src/networking.c.orig       2015-01-14 05:12:08 UTC
+++ src/networking.c
@@ -1,9 +1,9 @@
 #include <arpa/inet.h>
 #include <fcntl.h>
-#include <netinet/in.h>
-#include <netinet/tcp.h>
 #include <sys/socket.h>
 #include <sys/types.h>
+#include <netinet/in.h>
+#include <netinet/tcp.h>
 #include <sys/uio.h>
 #include <syslog.h>
 #include <unistd.h>

fixes it.

**Comment by opsec** [comment]
Also see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=196240

**Comment by armon** [comment]
@opsec Could you clarify the patch? It looks like it was only partially included.

**Comment by opsec** [comment]
Ups, sorry, cut and paste with the textfield. You can find it here:
https://lists.freebsd.org/pipermail/svn-ports-all/2015-January/083096.html

I'm not yet familiar with the process to submit the patch directly to github (sorry).

**Comment by armon** [comment]
@opsec That patch is just moving the import lower? Is that actually affecting things? I'm happy to move the import if it matters but it seems like it wouldn't.

**Comment by opsec** [comment]
Yes, it moves two includes below sys/types.h etc. Yes, it fixes the build on FreeBSD 8.4, where src/networking.c will not build otherwise.

**Comment by armon** [comment]
Cool, should be fixed!
