### ISSUE TITLE
Document recommended graphite aggregation methods for statsite metrics

### ISSUE THREAD

**Issue by afelle1** [armon/statsite#106]
It would help if there were documented recommendations on graphite storage aggregation for statsite metrics especially extended counters and timers.  Forgive me as I'm still thinking about this so not saying this is 100% right or recommended; just a place to start the conversation:

* Extended Counters:
  * .count

    > pattern = \\.count$
    > aggregationMethod = sum

  * .mean

    > pattern = \\.mean$
    > aggregationMethod = average

  * .stdev

    > pattern = \\.stdev$
    > aggregationMethod = average

  * .sum

    > pattern = \\.sum$
    > aggregationMethod = sum

  * .sum_sq

    > pattern = \\.sum_sq$
    > aggregationMethod = sum

  * .lower

    > pattern = \\.lower$
    > aggregationMethod = min

  * .upper

    > pattern = \\.upper$
    > aggregationMethod = max

  * .rate

    > pattern = \\.rate$
    > aggregationMethod = average
* Timers:

  * .sum

    > pattern = \\.sum$
    > aggregationMethod = sum

  * .sum_sq

    > pattern = \\.sum_sq$
    > aggregationMethod = sum

  * .mean

    > pattern = \\.mean$
    > aggregationMethod = average

  * .lower

    > pattern = \\.lower$
    > aggregationMethod = min

  * .upper

    > pattern = \\.upper$
    > aggregationMethod = max

  * .count

    > pattern = \\.count$
    > aggregationMethod = sum

  * .stdev

    > pattern = \\.stdev$
    > aggregationMethod = average

  * .median

    > pattern = \\.median$
    > aggregationMethod = average

  * .p95

    > pattern = \\.p95$
    > aggregationMethod = average

  * .p99

    > pattern = \\.p99$
    > aggregationMethod = average

  * .rate

    > pattern = \\.rate$
    > aggregationMethod = average

  * .sample_rate

    > pattern = \\.sample_rate$
    > aggregationMethod = average

**Comment by josephmc5** [comment]
@armon I would also be curious about what you guys use at HashiCorp or with clients

**Comment by armon** [comment]
@afelle1 @josephmc5  I'm no expert in graphite, so I can't provide much useful feedback. It seems reasonable to me however.
