### ISSUE TITLE
Initscript Dependencies

### ISSUE THREAD

**Issue by pitheist314** [armon/statsite#107]
In the provided initscript on line 69, there is a call to configtest.  None of the CentOS 6 boxes I have have that executable.  Google tends to lead me toward apachectl configtest or an nginx equivalent, which I'm assuming are unrelated.  What is purpose of that line, and what package is required to use it?

**Comment by armon** [comment]
I have no idea! It was contributed by somebody else. If you figure it out, I'd love a PR to fix it.
