### ISSUE TITLE
Support sampling for timer counts

### ISSUE THREAD

**Issue by mkavanagh** [armon/statsite#117]
StatsD adjusts timer counts according to the sample rate (see https://github.com/etsy/statsd/issues/139 - it doesn't appear to adjust anything else e.g. the sum). As far as I can tell Statsite doesn't support that currently - would be useful (to me!) if it did.

**Comment by armon** [comment]
This seems very sketchy to me. Since mathematically, all of the values are wrong if you are doing that kind of sampling. I'm not exactly sure what you gain.

**Comment by allouis** [comment]
:+1: for this feature

**Comment by drawks** [comment]
:-1: @armon is quite correct that none of the other values make sense to be adjusted for sampling. On the rendering side you could draw some confidence bands based on the count and the sample rate, but not every situation is going to result in the same stat math to determine appropriate bands for the given data set. To outsource this calculation to the collection layer and not the render layer is going to taint the data and make it less useful to someone who would actually be interested in using math appropriate to their own use case.

**Comment by armon** [comment]
I'm closing this, as I don't believe it makes sense statistically.
