### ISSUE TITLE
Documentation on binary protocol doesn't indicate any support for flags

### ISSUE THREAD

**Issue by drawks** [armon/statsite#120]
The protocol description includes a note about how flags are supported, this is typically used for indicating sample rate for counters. 

> By default, Statsite will listen for TCP and UDP connections. A message looks like the following (where the flag is optional)::
> `key:value|type[|@flag]`

whereas the binary protocol includes no description for a flags field. It is unclear whether flags are supported in the binary protocol and if they are how they are meant to be expressed.

**Comment by armon** [comment]
@drawks Unfortunately the binary protocol does not support any of the flags.

**Comment by drawks** [comment]
Ah bummer, that is rather unfortunate.
