### ISSUE TITLE
Streaming command exited with status 1

### ISSUE THREAD

**Issue by femuitar55** [armon/statsite#131]
Dear statsite team, 

 Not sure anyone has seen this issue before. I've got the following error in the system log

```
abrt: detected unhandled Python exception in 'sinks/graphite.py'
abrtd: New client connected
abrtd: Directory 'pyhook-<date>' creation detected
abrt-server[5510]: Saved Python crash dump of pid 4988 to /var/spool/abrt/pyhook<date>
statsite[24849]: Streaming command exited with status 1
abrtd: Package 'statsite' isn't signed with proper key
abrtd: 'post-create' on '/var/spool/abrt/pyhook-<date>' exited with 1
abrtd: Deleting problem directory '/var/spool/abrt/pyhook-<date>'

```

I've used the following configuration.
```
[statsite]
tcp_port = 8125
udp_port = 8125
bind_address = 127.0.0.1
log_level = INFO
flush_interval = 10
timer_eps = 0.01
set_eps = 0.02
stream_cmd = python <path>/sinks/graphite.py <graphite url> 2003 ""
global_prefix =
kv_prefix =
gauges_prefix =
counts_prefix =
sets_prefix =
timers_prefix =
daemonize = 1
pid_file=/var/run/statsite/statsite.pid
```

my os is Linux 2.6.32-431.5.1.el6.x86_64.

What I've tried to do is printing more log, just came up with this.
```
statsite[1124]: Listening on tcp '127.0.0.1:8125'
statsite[1124]: Listening on udp '127.0.0.1:8125'.
statsite[1124]: PID 1146
statsite[1146]: PID 0
statsite[1146]: Before Running python cmd: PID 0
statsite[1124]: Waitpid: PID 1146
abrt: detected unhandled Python exception in '<path>/sinks/graphite.py'
abrtd: New client connected
abrt-server[1148]: Saved Python crash dump of pid 1147 to /var/spool/abrt/pyhook-<date>
abrtd: Directory 'pyhook-<date>' creation detected
statsite[1124]: Streaming command exited with status 1
abrtd: Executable '<path>/sinks/graphite.py' doesn't belong to any package
abrtd: 'post-create' on '/var/spool/abrt/pyhook-<date>' exited with 1
abrtd: Corrupted or bad directory /var/spool/abrt/pyhook--<date>, deleting
```

Could you please advise if I did something incorrectly? Feel free to let me know if any more info required.

Thank you very much for your effort.

**Comment by armon** [comment]
@femuitar55 It looks like the sink is crashing for some reason. Statsite just does a fork/exec, so you can try to invoke the stream_cmd manually and investigate why its not able to run. Try:
```
$ python <path>/sinks/graphite.py <graphite url> 2003 ""
```

**Comment by femuitar** [comment]
Thank you for your response. It seems that I've got the graphite connection problem with the traceback below.
```
Traceback (most recent call last):
  File "/sinks/graphite.py", line 96, in _create_socket
    sock.connect((self.host, self.port))
  File "<string>", line 1, in connect
 [Errno 110] Connection timed out
```
I will fix in the sink script. Many thanks.

**Comment by armon** [comment]
My pleasure!

**Comment by chaturvedia** [comment]
@femuitar @armon Is there a fix needed? I also saw this on my system. Looking through the commits I do not see a fix

**Comment by armon** [comment]
@chaturvedia There is no bug in statsite, the script error is that the python script cannot connect to graphite, so its an operational issue not a software bug as far as I can tell

**Comment by breml** [comment]
@chaturvedia Do you use the latest version of the graphite sink? I added some exception handling in https://github.com/armon/statsite/commit/dafa94a0622cafa2fef3a93e26407030a4b4b1b9

If the problem still exists with the updated sink let me know.
