### ISSUE TITLE
AMQP support

### ISSUE THREAD

**Issue by duylong** [armon/statsite#134]
Hi, 

It would be interesting to add support for RabbitMQ.

RabbitMQ implements AMQP protocol in order to simplify the processing of messages (routing key, queue...).

Best regards,

**Comment by armon** [comment]
@duylong Do you mean as the sink destination? I'm not sure what you mean by this

**Comment by duylong** [comment]
It would be interesting to have in input and output:

* RabbitMQ => Statsite: We can retrieve the messages from the queues ;
* Statsite => RabbitMQ: We can manage the routing of messages to send them to the correct queues ;

Centralizing the flow enables us to better manage communication tools. You can see the exchange between tools and manage queues (useful for updating an application or in case of application failure). This support is for example already in Logstash (input/output), Sensu (Input/Output), Graphite (input), Collectd (output)...

**Comment by armon** [comment]
I think you can implement the `Statsite => RabbitMQ` path currently, you just need to write a custom sink (see the examples directory). The `RabbitMQ => Statsite` direction would only work if Rabbit supports emitting Statsd / Statsite compatible metrics.

**Comment by duylong** [comment]
RabbitMQ concerns only the transport, the content is free. Only requirement, use AMQP libraries: http://www.rabbitmq.com/devtools.html

I currently test collectd (plugin statsd + amqp output). If I need, I'll see to write a custom sink ;)
