### ISSUE TITLE
Gauges not on par with statsd

### ISSUE THREAD

**Issue by resnostyle** [armon/statsite#137]
We are seeing behavior unlike that of statsd with regards to gauges. In our particular case, gauges are displaying a constant value when view in graphite. 

We have made a few passes the graphite sink to try to feed the gauge value back into statsite and correct this behavior. Any chance full support for gauges will be added?

**Comment by dpkp** [comment]
you might take a look at #69 -- it has some more info on how statsite manages gauges

**Comment by armon** [comment]
@resnostyle That PR is a good place to look for context. Gauges do not "feed forward" in statsite, and so if you want that behavior it is best simulated by just looping the output back in.
