### ISSUE TITLE
sinks/influxdb.py incompatible since InfluxDB 0.9.0

### ISSUE THREAD

**Issue by maticmeznar** [armon/statsite#138]
InfluxDB v0.9 changed it's HTTP API, making this sink incompatible :(

**Comment by kuba--** [comment]
I've stopped maintaining that sink, but I can take a look how InfluxDB API has been changed in 0.9 and update it (to be compatible with old and new version).

**Comment by maticmeznar** [comment]
Oh man, that would be awesome! If you can make it work, I'll give a good prayer to Flying Spaghetti Monster for you :)

**Comment by kuba--** [comment]
https://github.com/armon/statsite/pull/140

**Comment by armon** [comment]
Fixed by #141

**Comment by maticmeznar** [comment]
Thank you!
