### ISSUE TITLE
Incorrect rate

### ISSUE THREAD

**Issue by mrwillihog** [armon/statsite#142]
Hi,

I've noticed that the rate is calculated incorrectly for counters and timers when used with a sample rate.

For example:

```js
setInterval(function() {
  statsite.timing('statsite', 100);
  statsite.timing('statsite.sampled', 100, 0.5);
}, 100);
```

This sends two timers, one sampled and one not. The rate of both should, I believe, be 10 as an event is sent every 100ms. However, the rate for the sampled timer is coming out at around 5.

I think the issue is that the timer count is always incremented by 1:

https://github.com/armon/statsite/blob/master/src/timer.c#L40

Where in actual fact it should be incremented by `1 / sampleRate`:

https://github.com/etsy/statsd/blob/master/stats.js#L259

Would you accept a PR that changes this to be compatible with StatsD?

**Comment by armon** [comment]
@mrwillihog Ah good catch, that is subtle. A PR would be great!
