### ISSUE TITLE
Any adjustments needed for graphite schema/aggregation configuration?

### ISSUE THREAD

**Issue by webframp** [armon/statsite#161]
The etsy/statsd implementation [docs specific to graphite](https://github.com/etsy/statsd/blob/master/docs/graphite.md) provide some guidance for schema and aggregation configuration.

Besides site specific changes needed, is there anything needing adjustment in order for these same recommendations to work correctly with statsite?

**Comment by armon** [comment]
Not really, you should be able to use the same configs as before!
