### ISSUE TITLE
influxdb sink

### ISSUE THREAD

**Issue by bscott** [armon/statsite#162]
Trying to get the InfluxDB sink working but running into an error.

```ERROR: Must provide METRIC_NAMESPACE```

Here is my statsite ini:

```
[statsite]
port = 8125
udp_port = 8125
log_level = INFO
log_facility = local0
flush_interval = 10
timer_eps = 0.01
set_eps = 0.02
STREAM_CMD=python /usr/local/lib/statsite/sinks/influxdb.py /etc/influxdb.ini INFO
```

and my influxdb.ini:

```
[influxdb]
host = influxdb
port = 8086
database = test
username = xxxx
password = xxxxx
prefix = statsite
version = 0.9
timeout = 10
```

**Comment by bscott** [comment]
Found issue, it was with the docker container I was using.

**Comment by jason-c-child** [comment]
@bscott what was the particular issue you had with the docker container?
