### ISSUE TITLE
make rpms dies due to .pyc's

### ISSUE THREAD

**Issue by Krylon360** [armon/statsite#170]
during the make rpms run; the task dies due to there are 2 .pyc's in the sinks/ dir. one for __init__.pyc and one for librato.pyc.

removing the 2 .pyc's and rerunning make rpms the task completes.

**Comment by armon** [comment]
@Krylon360 The pyc files are not part of the git repo, they would be there if you ran python however

**Comment by armon** [comment]
I'm going to close this, as the issue appears to be in the rpm and not the repository.
