### ISSUE TITLE
Centos 6 support

### ISSUE THREAD

**Issue by mrh666** [armon/statsite#173]
Hi there,

Any chance Centos 6 support can be added to statsite module?

**Comment by armon** [comment]
@mrh666 Does it not compile on CentOS 6? It should work on any relatively recent version of linux and gcc.

**Comment by mrh666** [comment]
It does, but I'm talking about Puppet module.

**Comment by armon** [comment]
@mrh666 I'm not sure exactly what you mean. You want the project to provide a puppet module? It's really a source only project, I'm sure there are existing modules on the forge. I don't personally know puppet, nor do I want to maintain it in the repository.

**Comment by mrh666** [comment]
Armon, my bad! I was sure this is your module! :)
