### ISSUE TITLE
RPM Spec Question

### ISSUE THREAD

**Issue by st-isidore-de-seville** [armon/statsite#175]
Hello.  It looks like in the RPM Spec file, it makes a comment that the RPM creates a statsite user and group however I do not see this present.  Is this potentially a feature that you would accept a PR for?  

Additionally do you have any guidance on packaging for Debian/Ubuntu?  Deb packages appear to be a dark art that I have not been able to crack :smile:

**Comment by filippog** [comment]
re: debian packaging, I made a debian package a while ago at http://git.wikimedia.org/summary/?r=operations/debs/statsite.git but haven't found the time to upload it to debian proper yet

**Comment by armon** [comment]
@st-isidore-de-seville All of the packaging has been community contributed, I'm not an expert on either RPM or Deb creation, so I don't have any guidance! If there is something missing form the RPC spec, I'd happily accept a PR

**Comment by st-isidore-de-seville** [comment]
@filippog, thanks I will check this out!
