### ISSUE TITLE
Incorrect p99 calculation - always equals upper

### ISSUE THREAD

**Issue by mhamrah** [armon/statsite#180]
When aggregating timers it appears the p99 calculation always equals the upper value. I'm not sure if I'm doing something wrong, but wanted to raise the issue for feedback.

Given the simple script:
 #!/bin/bash
```
   for i in `seq 1 1000`;
   do
     echo "foo:1|ms"  | nc -w0 localhost 8125
   done
   echo "foo:10000000|ms"  | nc -w0 localhost 8125
```

I expect the p99 output to be 1, like the p95, but it is 10000000:
```
timers.foo.sum|10001000.000000|1456499598
timers.foo.sum_sq|100000000001000.000000|1456499598
timers.foo.mean|9991.008991|1456499598
timers.foo.lower|1.000000|1456499598
timers.foo.upper|10000000.000000|1456499598
timers.foo.count|1001|1456499598
timers.foo.stdev|316069.739014|1456499598
timers.foo.median|1.000000|1456499598
timers.foo.p50|1.000000|1456499598
timers.foo.p95|1.000000|1456499598
timers.foo.p99|10000000.000000|1456499598
timers.foo.rate|1000100.000000|1456499598
timers.foo.sample_rate|100.100000|1456499598
```

The effect is true for small iterations as well:
```
timers.foo.sum|10000099.000000|1456500126
timers.foo.sum_sq|100000000000099.000000|1456500126
timers.foo.mean|100000.990000|1456500126
timers.foo.lower|1.000000|1456500126
timers.foo.upper|10000000.000000|1456500126
timers.foo.count|100|1456500126
timers.foo.stdev|999999.900000|1456500126
timers.foo.median|1.000000|1456500126
timers.foo.p50|1.000000|1456500126
timers.foo.p95|1.000000|1456500126
timers.foo.p99|10000000.000000|1456500126
timers.foo.rate|1000009.900000|1456500126
timers.foo.sample_rate|10.000000|1456500126
```

**Comment by armon** [comment]
@mhamrah This is likely an artifact of the lossy computation. Statsite specifically uses a lossy algorithm that allows it to trade a configurable error for massive gains in performance and memory utilization. Without investigating much more deeply, I think this is just an artifact of the algorithm and the relatively small input set size.

**Comment by mhamrah** [comment]
Cool, thanks.

- Curios, is this attributed to storing the timer values in a hyperloglog
set? Haven't dug deeply into the code.
- Is there a way the user can control the setting to make it less lossy?
- Any suggestion on how large the input needs to be? I've seen this
exhibited with as much as 50k records.

Thanks again,

Mike

**Comment by mhamrah** [comment]
Nevermind, I found the config setting. Thanks for the response.

**Comment by armon** [comment]
@mhamrah I got curious and wrote a test for this, looks like it was a bug! Here is the fix: https://github.com/armon/statsite/commit/828d7d75c9156edef82d10dc32fb7c95388bccff here is the test based on your repro case: https://github.com/armon/statsite/commit/484e3ebee8629890ae36c6b4858baee62e202e7e.

Thanks!

**Comment by mhamrah** [comment]
Oh nice, thanks!

**Comment by mhamrah** [comment]
It was interesting because playing around with the setting today showed
that .01 resulted in an error but .009 didn't.

**Comment by armon** [comment]
@mhamrah Yeah something was bothering me about it... I guess the default eps of 1% at the 99 percentile interacts jus perfectly to give you the upper bound value every time, which is odd.
