### ISSUE TITLE
Convert to make

### ISSUE THREAD

**Issue by johnkeates** [armon/statsite#181]
Would it be okay to convert from scons to make? Debian and derivatives will have better support for automated packaging and distribution when using a supported build system.

**Comment by armon** [comment]
@johnkeates I'd be happy to accept a PR, but I don't know enough about autotools to do this efficiently

**Comment by johnkeates** [comment]
@armon So, two days later, I figured I don't know enough about autotools either to do this fast and efficiently. The reason I aimed for converting it was because Debian and derivatives like autotools-based projects in their packaging automation. One of the reasons seems to be the use of automated patching and overriding, which depends amongst others, on passing parameters to make via environment variables.

After I dug a bit further, it seems there should be an easier way using scons to generate a .deb package directly, so I'll aim my efforts at that. Since there doesn't seem to be a lot of interest in make at this point, I'm clicking close on my own issue and once I have figured out how to add deb-dpkg as a build target I'll submit a PR.
