### ISSUE TITLE
Tacked on Debian Package support

### ISSUE THREAD

**Issue by johnkeates** [armon/statsite#182]
So, I made a first pass at adding support for creating a debian package. At this point it does work fine and creates a package. I used the .service file and config example from the rpm package setup, as well as the /usr/libexec path suggestion.

Link to the current WIP commit: https://github.com/armon/statsite/compare/master...johnkeates:master

I'll clean up and structure it somewhat better, as well as add scripts to start/stop the service on installation and removal etc. and maybe add an attempt to make it more debian-compatible. At the moment, it does the basic stuff you need: put the files in the right spot using dpkg. It installs and uninstalls and upgrades, so the biggest items are working!

I'm not submitting a PR just yet, if you have any ideas or suggestions on how this would integrate better with the project I'd love to hear it. Oh, and it put the SConstruct file through flake and made a tiny amount of formatting cleanups, but those are not that important.

**Comment by filippog** [comment]
@johnkeates FWIW this is what we are using at WMF https://github.com/wikimedia/operations-debs-statsite/tree/master/debian needs updating too before uploading to Debian (see also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778731)

**Comment by johnkeates** [comment]
I've been thinking about getting back to my original target to convert this project from scons to Make and maybe the complete autotools stack. At my first attempt there wasn't much support and my autotools knowledge was lacking, but I've since read and tried so many things that I want to try again, probably with more success this time.

**Comment by johnkeates** [comment]
And, some time later, I can now successfully build the package using autotools and 'standard' make.

@filippog do you think it's worth combining the effort and maybe team up to become the debian maintainers? I have never maintained a package, but how hard could it be?

**Comment by johnkeates** [comment]
Seems to work, at least for a basic run to end up with a working binary: https://travis-ci.org/johnkeates/statsite/builds/116426308

@armon Aside from the tests, is there anything I should consider before cleaning this autotools conversion up and submitting a PR? I think I'll end up removing scons, but in theory they could coexist.

**Comment by armon** [comment]
@johnkeates I would leave scons alongside for now, but I can't think of anything else!

**Comment by johnkeates** [comment]
I'll leave it in, and add the scons tests as well as maybe make a build-scons target that uses scons instead of whatever configure thinks. I'm also thinking about trying to modify the autotools setup a bit so it can create completely identical builds. Right now the hash differs and it's using cc instead of gcc, statsite does work fine but my compiler knowledge isn't good enough to know if there is any actual difference at runtime.
