### ISSUE TITLE
Statsite fails to start

### ISSUE THREAD

**Issue by lakshmi-github** [armon/statsite#185]
I get this error when I tried to start stat site. I have verified that a normal user can open a socket on port 8125. Any ideas on why this could be?

service statsite start
Starting statsite: statsite[28239]: Starting statsite.
statsite[28239]: stdin is disabled
statsite[28239]: Failed to bind on any TCP socket!
statsite[28239]: Failed to initialize networking!
                                                           [FAILED]

Thanks,
Lakshmi

**Comment by armon** [comment]
@lakshmi-github Hmm I'm not sure, it seems like the TCP bind is failing. Have you tried to explicitly configure the IP and Port it is binding to?

**Comment by lakshmi-github** [comment]
@armon that was it, I set the bind_address to localhost or fqdn, and it came up.

bind_address= <fqdn>
port=8125
udp_port=8125

Thanks.
