### ISSUE TITLE
Optional Quantiles

### ISSUE THREAD

**Issue by hoffoo** [armon/statsite#188]
Is it possible set the timer quantiles as optional?

For our use case, we send a ton of metrics to librato and for many of them we don't need quantiles. This would help cut down on our bill.

I wouldn't mind doing this, just wondering if its something others would find useful

Thanks!

**Comment by armon** [comment]
@hoffoo The simplest way is probably to just run the output of statsite through grep. Think of the output as a simple stream, so just filter out the metrics you don't want before it goes to the librato sink.
