### ISSUE TITLE
Make is failing

### ISSUE THREAD

**Issue by priya23** [armon/statsite#192]
Hi,
I using an ubuntu machine,after running configure during make the installation is failing with following error:
	mv -f $depbase.Tpo $depbase.Po
gcc -g -std=gnu99 -pthread -D_GNU_SOURCE -DLOG_PERROR=0 -O3 -pthread -lm -lrt -Ideps/inih/ -Ideps/ae/ -Isrc/ -g -O2   -o src/statsite src/hashmap.o src/heap.o src/radix.o src/hll_constants.o src/hll.o src/set.o src/cm_quantile.o src/timer.o src/counter.o src/metrics.o src/streaming.o src/config.o src/networking.o src/conn_handler.o src/statsite.o deps/ae/libae.a deps/inih/libinih.a deps/murmurhash/libmurmur.a 
src/hll.o: In function `hll_init':
/data/statsite/src/hll.c:48: undefined reference to `ceil'
src/hll.o: In function `raw_estimate':
/data/statsite/src/hll.c:148: undefined reference to `pow'
src/hll.o: In function `linear_count':
/data/statsite/src/hll.c:161: undefined reference to `log'
src/hll.o: In function `hll_precision_for_error':
/data/statsite/src/hll.c:267: undefined reference to `log2'
/data/statsite/src/hll.c:268: undefined reference to `ceil'
src/set.o: In function `set_size':
/data/statsite/src/set.c:109: undefined reference to `ceil'
src/cm_quantile.o: In function `cm_cursor_increment':
/data/statsite/src/cm_quantile.c:220: undefined reference to `ceil'
/data/statsite/src/cm_quantile.c:220: undefined reference to `ceil'
src/cm_quantile.o: In function `cm_query':
/data/statsite/src/cm_quantile.c:166: undefined reference to `ceil'
src/cm_quantile.o:/data/statsite/src/cm_quantile.c:169: more undefined references to `ceil' follow
src/timer.o: In function `timer_stddev':
/data/statsite/src/timer.c:99: undefined reference to `sqrt'
src/counter.o: In function `counter_stddev':
/data/statsite/src/counter.c:68: undefined reference to `sqrt'
src/conn_handler.o: In function `str2double':
/data/statsite/src/conn_handler.c:432: undefined reference to `pow'
collect2: error: ld returned 1 exit status
make[1]: *** [src/statsite] Error 1
make[1]: Leaving directory `/data/statsite'
make: *** [all-recursive] Error 1

Its not able to identify math functions .Can you help out in this.

**Comment by johnkeates** [comment]
It looks like it's trying to include it ( -lm in the gcc params), but for some reason it fails anyway.

Since you are on ubuntu; did you try 'sudo apt install build-essential' first?

**Comment by priya23** [comment]
it worked now..thanks
