### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by falzm** [armon/statsite#193]
Hi

It's been almost a year and 110 commits since the latest stable release: could you release a new version? For instance the `extended_counters_include` setting is documented but not available in the current version, which is misleading...

**Comment by armon** [comment]
@falzm Sure, I will wait on a PR and then tag the next release!

**Comment by falzm** [comment]
Hi, any updates on a new release?

**Comment by armon** [comment]
Just tagged e69cf74 as the v0.8.0 release!

**Comment by falzm** [comment]
Great, thank you!
