### ISSUE TITLE
Reg:Streaming command exited with status 1

### ISSUE THREAD

**Issue by priya23** [armon/statsite#200]
Hi,
I am evaluating a situation in which backend sink will fail i saw that the server keeps trying to connect to backend as i have set it in daemonize mode.If i have to stop it after some number of retry where should i put the condition i saw src/conn_handler.c  file is handling it ,clarify if i am wrong.

**Comment by priya23** [comment]
i would also like to know if the backend sink is down what will happen to data .will it flush the complete data after flush interval?
and will it keep on trying continousoly?

**Comment by armon** [comment]
@priya23 statsite will invoke the sink only once and send the data. Most of the sinks implement retry logic to talk to the backend (for example the graphite sink), however statsite does not have any retry logic itself, as its invoking a local handler and does not expect network failures. Hope that helps!
