### ISSUE TITLE
Invalid data being sent to sink

### ISSUE THREAD

**Issue by mike-lerch** [armon/statsite#201]
I have been able to reproduce this issue on `0.6.5`, `0.7.1`, and `0.8.0`

Setup is running `CentOS 6.4` and statsite built with glibc `2.12-1.107`

I am having this in a larger environment, but I was able to reproduce this in a lab as well. Data coming into our sinks is randomly malformed, and it always affects the beginning of the line. I believe another pattern may be that it is always the last gauge or first timer, or during the transition from one type to another in the sink.

Lab Setup:

We start statsite by running `/usr/local/bin/statsite -f ~/statsite.conf` where `statsite.conf` contains:
```
[statsite]
port = 8125
udp_port = 8125
log_level = INFO
flush_interval = 10
timer_eps = 0.001

stream_cmd = tee - > statsite.raw.log.`date +%s`
daemonize = false
```

We then start an instance of consul `0.6.3` in the lab, specifying a statsite address. Note that we are experiencing this issue with all clients, not just consul, so I am only using consul as one example.

```
echo '{"client_addr": "127.0.0.1", "statsite_addr": "127.0.0.1:8125", "statsite_prefix": "tcp-consul"}' | consul agent -server -bind 127.0.0.1 -dev -node localhost -config-file /dev/stdin
```

And just for testings sake, we will also start a second instance, but this time using the `statsd` configuration, which will deliver over UDP:

```
ifconfig lo:1 127.0.0.2
echo '{"client_addr": "127.0.0.2", "statsd_addr": "127.0.0.1:8125"}' | consul agent -server -bind 127.0.0.2 -dev -node localhost -config-file /dev/stdin
```

After leaving the above setup running for several minutes, we get timestamped files for every sink:
```
# ls -l statsite.raw.log.* | head -n5
-rw-r--r-- 1 root root 32698 Jun 19 02:22 statsite.raw.log.1466302929
-rw-r--r-- 1 root root 22728 Jun 19 02:22 statsite.raw.log.1466302939
-rw-r--r-- 1 root root 29246 Jun 19 02:22 statsite.raw.log.1466302949
-rw-r--r-- 1 root root 15788 Jun 19 02:22 statsite.raw.log.1466302959
-rw-r--r-- 1 root root 24594 Jun 19 02:22 statsite.raw.log.1466302969
```

Most files are in the proper syntax:
```
# head -n5 statsite.raw.log.1466302929
counts.consul.raft.apply|1.000000|1466302929
counts.tcp-consul.raft.barrier|1.000000|1466302929
timers.consul.serf.queue.Query.sum|0.000000|1466302929
timers.consul.serf.queue.Query.sum_sq|0.000000|1466302929
timers.consul.serf.queue.Query.mean|0.000000|1466302929
```

However, the following grep with regex returns a bunch of lines that do not start with a metric type:
```
# grep -vE "^(gauges|timers|counts)\." statsite.raw.log.* | head -n5
statsite.raw.log.1466302929:Intent.p95|0.000000|1466302929
statsite.raw.log.1466302939:.Event.mean|0.500000|1466302939
statsite.raw.log.1466302949:1466302949
statsite.raw.log.1466302969:um_sq|10.000000|1466302969
statsite.raw.log.1466302979:466302979
```

And here are examples of what the file contents are, which are totally unexpected:
```
# grep -A2 -B2 -E "^Intent" statsite.raw.log.1466302929
gauges.consul.localhost.runtime.heap_objects|3612.000000|1466302929
gauges.consul.localhost.consul.session_ttl.active|0.000000|1466302929
Intent.p95|0.000000|1466302929
timers.consul.serf.queue.Intent.p99|0.000000|1466302929
timers.consul.serf.queue.Intent.rate|0.000000|1466302929
```

```
# grep -A2 -B2 -E "^um" statsite.raw.log.1466302969
gauges.consul.localhost.runtime.heap_objects|13140.000000|1466302969
gauges.consul.localhost.consul.session_ttl.active|0.000000|1466302969
um_sq|10.000000|1466302969
timers.tcp-consul.serf.queue.Event.mean|0.500000|1466302969
timers.tcp-consul.serf.queue.Event.lower|0.000000|1466302969
```

```
# grep -A2 -B2 -E "^60" statsite.raw.log.1466303609
gauges.consul.localhost.runtime.heap_objects|8667.000000|1466303609
gauges.consul.localhost.consul.session_ttl.active|0.000000|1466303609
609
timers.consul.memberlist.gossip.p99|0.024008|1466303609
timers.consul.memberlist.gossip.rate|0.050740|1466303609
```

I understand this is pretty odd behavior but I am out of ideas as to what may be causing this. Do you have any ideas?

**Comment by mike-lerch** [comment]
If anyone stumbles onto something like this in the future, the issue was here:

```
stream_cmd = tee - > statsite.raw.log.`date +%s`
```

When we were testing this on OSX, things worked as we thought they would.
```
$ echo test | tee -> test
$ cat test
test
$
```

But then in our lab and production environments, we are running Linux:
```
$ echo test | tee - > test
$ cat test
test
test
$
```

Things end up piping twice in linux, and the file is being written by two places at once. We've removed the tee command entirely as it was no longer needed.

**Comment by farvour** [comment]
EUE :)
