### ISSUE TITLE
configure statsite server on nginx

### ISSUE THREAD

**Issue by jindov** [armon/statsite#202]
I want to use statsite instead of statsd, but it (statsite) cannot use directive "statsd_server statsd.server.com;" in nginx.conf file to inform that where is stats server. So I wonder how to combine nginx_statsd_module with statsite?Does it possible?

**Comment by luca3m** [comment]
statsite is wire compatible with statsd, so it should work as a drop-in replacement.

**Comment by armon** [comment]
I think @luca3m answered this, you can just point it to the IP:Port of statsite and it should work!
