### ISSUE TITLE
0.8.0 spec file has wrong version

### ISSUE THREAD

**Issue by mike-lerch** [armon/statsite#205]
The 0.8.0 tag has an rpm spec file that builds as version 0.7.1.

See: https://github.com/armon/statsite/blob/v0.8.0/rpm/statsite.spec

**Comment by mike-lerch** [comment]
It also appears 0.7.1 is still set here as well: https://github.com/armon/statsite/blob/v0.8.0/configure.ac#L4-L8

**Comment by armon** [comment]
Fixed by #203
