### ISSUE TITLE
What does the flag option do in the metric protocol?

### ISSUE THREAD

**Issue by trienism** [armon/statsite#207]
Hi, 

I was hoping to find an example of how to use the flag option in the documentation?

   `key:value|type[|@flag]`

What does it do exactly?

Also, is there a way to add meta data to a metric without obstructing the metric name?

**Comment by fabeschan** [comment]
+1

**Comment by armon** [comment]
@trienism It depends on the metric type. For example, with counters, it changes the sample rate (e.g. 0.1 means 1/10 are being sampled). This changes how the aggregation is done. The flags should be treated the same as with the Etsy statsd implementation.
