### ISSUE TITLE
Streaming handoff does not work for BusyBox

### ISSUE THREAD

**Issue by dankuna** [armon/statsite#209]
On an embedded linux system using Busybox (https://busybox.net/), `/bin/sh` is really just a symlink to `busybox`. `busybox` then infers which program it should run from argv[0]. The code in `src/streaming.c` attempts to trick `sh` into thinking its name is `streaming`, by passing `"streaming"` as argument 1 of the `execl()` call:
```
res = execl("/bin/sh", "streaming", "-c", cmd, NULL);
```
Busybox then rejects the attempts to run the streaming command by responding with:
```
streaming: applet not found
```

If possible, would recommend changing the `execl()` call to:
```
res = execl("/bin/sh", "sh", "-c", cmd, NULL);
```
as this should support both busybox and non-busybox systems. I haven't really tested thoroughly enough to verify that this doesn't break anything and that the streaming hooks don't depend on argv[0] being `"streaming"`, so I figured I'd ask if this would be possible. I'm happy to submit a pull if you think it's a workable idea.

**Comment by armon** [comment]
@dankuna Happy to accept a PR for it, it's a known issue for busy box.
