### ISSUE TITLE
Add install targets into scons

### ISSUE THREAD

**Issue by Lupus** [armon/statsite#86]
I was trying to build a deb package using debhelper built-in support for scons, and the resulting package was empty.

Looking further it appears that scons script is missing install targets for the resulting binary and sink commands. We've worked around this issue by listing the required files straight in `debian/install` file, but Debian policy suggests against it, so It would be nice to have install targets added upstream.

**Comment by armon** [comment]
I think we will leave this outside the scope of the scons file, since then we need to solve for many different systems.
