### ISSUE TITLE
Bug in circbuf_write

### ISSUE THREAD

**Issue by rishid** [armon/statsite#98]
I believe there is a bug (I am surprised I haven't seen this hit in production yet) in the circbuf_write method.  The second parameter of the memcpy, "in" should be "in + end_size"

https://github.com/armon/statsite/blob/master/src/networking.c#L1026

**Comment by armon** [comment]
Good catch! Super subtle. Statsite never responds and so circbuf_write is never invoked. This does affect bloomd and hlld however, so I've copied the fix there too!
